### PR TITLE
Fix the inputs check in PIOc_Init_Intracomm()

### LINKED ISSUE #131: Inputs are incorrectly checked in PIOc_Init_Intracomm()
In PIOc_Init_Intracomm(), there is a check on the inputs:
```
/* Check the inputs. */
if (... || num_iotasks * stride > num_comptasks)
    return pio_err(NULL, NULL, PIO_EINVAL, __FILE__, __LINE__);
```
For E3SM test SMS_D_Ln5.ne4_ne4.FC5AV1C-L run on Cori, the
inputs can be:
`base = 0, num_iotasks = 2, stride = 67, num_comptasks = 128`

The above check fails for this case as 2 * 67 = 134 > 128
Obviously, something is wrong with this check, as the 2 IO tasks
can be 0 and 67 ranks.

There is no existing PIO unit test to reproduce this kind of issue
so we can add a new one for it.

The correct check should be something like below:
```
if (... || stride * (numiotasks - 1) >= num_comptasks)
    return pio_err(NULL, NULL, PIO_EINVAL, __FILE__, __LINE__);
```
This check uses 0 as the PIO root (base), calculates the last IO
task's rank and makes sure that rank is still within the bounds. 

Note, this check does not use the actual base. If this check passes
and the actual base > 0, PIO performs a circular shift to set the rank
of the first IO task to base:
```
for (int i = 0; i < ios->num_iotasks; i++)
{
    ios->ioranks[i] = (base + i * ustride) % ios->num_comptasks;
    ...
}
```

### PR DESCRIPTION
**Pull request by dqwu**
The existing inputs check in PIOc_Init_Intracomm() uses an
incorrect formula, which has caused 4 e3sm_developer tests
with valid inputs to fail on Cori.

Added a new unit test to reproduce this bug and updated the
inputs check to make it pass. The 4 e3sm_developer tests also
pass with this fix.

Also removed a wrong test that fails with the new inputs check.

Fixes #131

### CODE REVIEW

File: src/clib/pioc.c [hunk 1]
```diff
@@ -804,7 +804,10 @@ int PIOc_Init_Intracomm(MPI_Comm comp_comm, int num_iotasks, int stride, int bas
         return check_mpi2(NULL, NULL, mpierr, __FILE__, __LINE__);
 
     /* Check the inputs. */
-    if (!iosysidp || num_iotasks < 1 || num_iotasks * stride > num_comptasks)
+    if (!iosysidp || num_iotasks < 1 || num_iotasks > num_comptasks ||
+        stride < 1 || stride > num_comptasks ||
```
Comment (jayeshkrishna) [inline src/clib/pioc.c]: stride > num_comptasks should be ok
e.g. stride = 128, num io tasks = 1, base = 0

Comment (dqwu) [reply src/clib/pioc.c]: An existing unit test (in test_iosystem2_simple2.c) has inputs:
stride = 31, num comp tasks = 1, num io tasks = 1, base = 0
It is treated as invalid inputs. If we allow stride > num_comptasks
in this case, the inputs will be valid and that test will fail.

Comment (jayeshkrishna) [reply src/clib/pioc.c]: The test is probably wrong

Comment (dqwu) [reply src/clib/pioc.c]: OK, I will remove that wrong test as well.
