### PR TITLE
Resolve overlapped run time for PIOc_sync and PIOc_closefile 

### LINKED ISSUE #223: Remove ncmpi_sync call from PIO2
It has already been removed in NCAR's PIO2 repo.

We have seen ncmpi_sync call takes a long time on anlworkstation and Summit (on Cori it is almost 0 cost).

Below is a GPTL timer on this call (from a high-res G case run on Summit):
`"o:ncmpi_sync"                                   -        195      195 2.359500e+04   1.179360e+04    61.436 (  7770      0)    59.564 (  4536      0)`

One comment from PnetCDF key developer Wei-keng:
> ncmpi_sync itself does nothing but simply calls MPI_File_sync.
> It is expected to have a very high cost, as MPI_File_sync (internally calls POSIX sync)
> is designed to ensure the data is safely stored on the disk hardware, before the
> function returns. People use it for extremely cautious behavior.
>  
> You do not need to call ncmpi_sync before ncmpi_close in PIO.
>  
> I also suggest to remove all ncmpi_sync from PIO internal functions.
> We should let application users to decide whether to “sync” to disks
> by them making an explicit call to a PIO disk sync API in their applications,
> if such a separate PIO function exists (that only calls ncmpi_sync).

Another comment:
> POSIX sync usually incurs a huge performance penalty.
> MPI_File_sync calls it and ncmpi_sync calls MPI_File_sync.
>  
> The term “sync" should not be confused with “flush”.
> Sync will guarantee the data is safely stored on the hard disks
> before the function call returns. Safe means even if file servers
> crashed right after the function returns, data is safely stored on disks.
> In parallel file systems like Lustre, there could be other penalties.

### LINKED ISSUE #225: PIOc_sync() contains some time spent in PIOc_closefile()
In existing PIO2 code, PIOc_closefile() calls PIOc_sync() to flush data to disk. As a result, a timer used to capture the cost of PIOc_closefile() would include the cost of the PIOc_sync() call inside the function. Since PIOc_sync() can be directly called by the user, it also includes a timer to capture the cost of the function. This makes measuring PIO performance difficult because,

* Adding the timers for PIOc_closefile() and PIOc_sync() would count the cost of PIOc_sync() calls from PIOc_closefile() twice
* Only using timers for PIOc_closefile() would ignore the cost of PIOc_sync() calls from the user

So it is a bad idea to directly call a user API from an another user API.

We can introduce an internal helper function to perform sync operations, and then call it inside PIOc_sync() and PIOc_closefile().

### PR DESCRIPTION
**Pull request by dqwu**
In existing PIO2 code, PIOc_closefile() calls PIOc_sync() to flush
data to disk. As a result, a timer used to capture the cost of
PIOc_closefile() would include the cost of the PIOc_sync() call
inside the function.

A new internal helper function, sync_file(), is introduced to perform
sync operations. It is used by both PIOc_sync() and PIOc_closefile(),
such that they no longer have overlapped run time.

Also, we choose not to call ncmpi_sync() for PIO_IOTYPE_PNETCDF
inside sync_file(), as that PnetCDF API has been confirmed to have a
very high cost on some systems.

Fixes #225
Fixes #223

### CODE REVIEW

File: src/clib/pio_file.c [hunk 1]
```diff
@@ -481,103 +595,7 @@ int PIOc_sync(int ncid)
...
-#ifdef _NETCDF
-            case PIO_IOTYPE_NETCDF:
-                if (ios->io_rank == 0)
-                    ierr = nc_sync(file->fh);
-                break;
-#endif
-#ifdef _PNETCDF
-            case PIO_IOTYPE_PNETCDF:
-                flush_output_buffer(file, true, 0);
-                ierr = ncmpi_sync(file->fh);
```
Comment (jayeshkrishna) [inline src/clib/pio_file.c]: Can you remove ncmpi_sync in a separate commit (One commit that just moves all the logic to a separate function and a second commit that removes ncmpi_sync() from the new function)?

**Comment by dqwu** [comment]
@jayeshkrishna 
Thanks for the suggestion. This PR has been updated, please check.
