### PR TITLE
Fix warnings in the code

### LINKED ISSUE #233: Fix all warnings with GNU on master
There are a bunch of warnings when building master with "-Wall" (gcc 6.2.0, anlworkstation).
* Unused variable/function warnings (almost all of the warnings belong to this category)
* comparison between signed/unsigned numbers
* conversion issues (loss of precision etc)
* Implicitly declared variables

### PR DESCRIPTION
**Pull request by jayeshkrishna**
This PR removes most of the warnings in the code
with the gnu 6.2.0 compiler.

Fixes #233

### CODE REVIEW

**Comment by jayeshkrishna** [comment]
Most of the remaining warnings are related to conditional compilation of code (e.g. "unused variables" when the source using the variable is disabled by a pre processor macro setting etc)

**Comment by jayeshkrishna** [comment]
Remaining warnings in the library source :
* GPTL warnings : Some of these are due to conditional compilations (unused variable), and we may not want to modify the code too much at this point
* snprintf warnings : Warnings like,
```
...directive output may be truncated writing x bytes ...
```
 can be ignored for now. They indicate that we are potentially truncating writing x (>y) bytes into a buffer with y bytes, but we ensure that no buffer overflow occurs in these cases.
* Some warnings on functions that are part of an interface,
```
Warning: ‘inq_*_desc’ defined but not used
```
 No idea why the compiler complains here. These functions are part of an interface and could potentially be used by user code (I did try removing instances of source where other functions that are part of the same interface were used directly but that did not help here). For now I think we should just ignore these
* 
```
Warning: Unused variable ‘q’ declared at (1) [-Wunused-variable]
```
 These are generated due to conditional compilation of the source. We could get rid of these warnings by declaring these variables conditionally, but IMO it just clutters up the code
*
```
Warning: ‘put_vara_internal_text’ defined but not used
```
 This function is autogenerated (for all supported types), so I think we should leave it as it is for now.
* "Unused dummy argument " warnings. These dummy arguments are required to maintain interface compatibility with PIO1.

File: tests/performance/pioperformance_rearr.F90 [hunk 1]
```diff
@@ -12,7 +12,7 @@ program pioperformance_rearr
         pio_rearr_opt_t, pio_rearr_comm_p2p, pio_rearr_comm_coll,&
         pio_rearr_comm_fc_2d_disable, pio_rearr_comm_fc_1d_comp2io,&
         pio_rearr_comm_fc_1d_io2comp, pio_rearr_comm_fc_2d_enable,&
-        pio_rearr_comm_unlimited_pend_req
+        pio_rearr_comm_unlimited_pend_req, PIO_NOERR
```
Comment (dqwu) [inline tests/performance/pioperformance_rearr.F90]: Although Fortran is not case-sensitive (most people now write
lower-case since this is more legible), other pio_types in this
file are written in lower-case. To be consistent, it is better
to use pio_noerr instead (throughout this file).

Comment (jayeshkrishna) [reply tests/performance/pioperformance_rearr.F90]: I think we should use "ALL CAP"s for constants

Comment (dqwu) [reply tests/performance/pioperformance_rearr.F90]: OK, then we can change constants in the existing Fortran code to use "ALL CAP" (maybe in a later code cleanup PR).

**Comment by dqwu** [comment]
@jayeshkrishna 
There are still 109 remaining warnings (reduced from 512):
https://my.cdash.org/viewBuildError.php?type=1&buildid=1685505

See if some of these warnings can be fixed.

**Comment by jayeshkrishna** [comment]
I went through the warnings and am not sure if we want to fix these right now. Did you have any specific warnings in mind?
* Some of the warnings fall into the categories described above (not going to fix now)
* The GPTL warnings : We might want to be careful in not to change the code too much (also most of the warnings are related to conditional code compilation etc)

Let me know if you have any specific warnings in mind and we can fix them too,

**Comment by jayeshkrishna** [comment]
We might want to bring in a newer version of GPTL in PIO to match the version used with E3SM. Once we bring in this new version we can decide on how to handle the warnings (ignore/fix) in GPTL.
